import { titilliumWeb } from "@/styles/global";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${titilliumWeb.className} bg-two text-slate-50 flex justify-center text-xl`}
      >
        {children}
      </body>
    </html>
  );
}
